/**
 * Policy template library: pre-built policies for common compensation scenarios.
 * Users can add these to their policy set via "Add from library" in the Policy Rules tab.
 * Each template is copied with fresh IDs when added.
 */

import type { AnnualIncreasePolicy } from '../types/compensation-policy';

function ts() {
  return new Date().toISOString();
}

/** Template key used by Compare Scenarios "conservative cap" preset. Single source of truth for that cap. */
export const CONSERVATIVE_CAP_TEMPLATE_KEY = 'cap-max5';

/** Get the conservative cap template (used by scenario presets). */
export function getConservativeCapTemplate(): (typeof POLICY_TEMPLATES)[number] | undefined {
  return POLICY_TEMPLATES.find((t) => t.templateKey === CONSERVATIVE_CAP_TEMPLATE_KEY);
}

/** Generate a fresh policy copy with unique IDs. */
export function instantiateTemplate(
  template: Omit<AnnualIncreasePolicy, 'id' | 'key'> & { templateKey: string },
  suffix = ''
): AnnualIncreasePolicy {
  const id = `pol-${template.templateKey}${suffix ? `-${suffix}` : ''}-${Date.now()}`;
  const key = `${template.templateKey}${suffix ? `-${suffix}` : ''}-${Date.now()}`;
  return {
    ...template,
    id,
    key,
    createdAt: ts(),
    updatedAt: ts(),
  };
}

/** Policy templates grouped by stage. */
export const POLICY_TEMPLATES: Array<{
  templateKey: string;
  name: string;
  description: string;
  stage: AnnualIncreasePolicy['stage'];
  policyType: string;
  policy: Omit<AnnualIncreasePolicy, 'id' | 'key'> & { templateKey: string };
}> = [
  // ─── EXCLUSION_GUARDRAIL ─────────────────────────────────────────────────
  {
    templateKey: 'guardrail-tcc75',
    name: 'High TCC guardrail',
    description: 'If current TCC percentile > 75, force 0% and flag for manual review.',
    stage: 'EXCLUSION_GUARDRAIL',
    policyType: 'Guardrail',
    policy: {
      templateKey: 'guardrail-tcc75',
      name: 'High TCC guardrail',
      description: 'If current TCC percentile > 75, force 0% and flag for manual review.',
      status: 'active',
      stage: 'EXCLUSION_GUARDRAIL',
      policyType: 'Guardrail',
      priority: 10,
      targetScope: {},
      conditions: { and: [{ '>': [{ var: 'tccPercentile' }, 75] }] },
      actions: [{ type: 'ZERO_OUT_INCREASE' }, { type: 'FLAG_MANUAL_REVIEW', metadata: 'TCC above 75th' }],
      conflictStrategy: 'FORCE_RESULT',
      stopProcessing: true,
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'guardrail-fmv-75th',
    name: 'FMV cap – TCC above 75th percentile',
    description: 'Fair market value: if current TCC percentile > 75, force 0% increase. Takes precedence over all other policies (runs first).',
    stage: 'EXCLUSION_GUARDRAIL',
    policyType: 'Guardrail',
    policy: {
      templateKey: 'guardrail-fmv-75th',
      name: 'FMV cap – TCC above 75th percentile',
      description: 'Fair market value: TCC > 75th → 0% increase. Takes precedence over other policies.',
      status: 'active',
      stage: 'EXCLUSION_GUARDRAIL',
      policyType: 'Guardrail',
      priority: 5,
      targetScope: {},
      conditions: { and: [{ '>': [{ var: 'tccPercentile' }, 75] }] },
      actions: [{ type: 'ZERO_OUT_INCREASE' }, { type: 'FLAG_MANUAL_REVIEW', metadata: 'FMV: TCC above 75th' }],
      conflictStrategy: 'FORCE_RESULT',
      stopProcessing: true,
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'guardrail-tcc90',
    name: 'Very high TCC guardrail',
    description: 'If TCC percentile > 90, zero out and require manual review.',
    stage: 'EXCLUSION_GUARDRAIL',
    policyType: 'Guardrail',
    policy: {
      templateKey: 'guardrail-tcc90',
      name: 'Very high TCC guardrail',
      description: 'If TCC percentile > 90, zero out and require manual review.',
      status: 'active',
      stage: 'EXCLUSION_GUARDRAIL',
      policyType: 'Guardrail',
      priority: 5,
      targetScope: {},
      conditions: { and: [{ '>': [{ var: 'tccPercentile' }, 90] }] },
      actions: [{ type: 'ZERO_OUT_INCREASE' }, { type: 'FLAG_MANUAL_REVIEW', metadata: 'TCC above 90th' }],
      conflictStrategy: 'FORCE_RESULT',
      stopProcessing: true,
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'guardrail-low-performer',
    name: 'Low performer guardrail',
    description: 'Evaluation score ≤ 2 flags for manual review (no zero-out).',
    stage: 'EXCLUSION_GUARDRAIL',
    policyType: 'Guardrail',
    policy: {
      templateKey: 'guardrail-low-performer',
      name: 'Low performer guardrail',
      description: 'Evaluation score ≤ 2 flags for manual review.',
      status: 'active',
      stage: 'EXCLUSION_GUARDRAIL',
      policyType: 'Guardrail',
      priority: 15,
      targetScope: {},
      conditions: { and: [{ '<=': [{ var: 'evaluationScore' }, 2] }] },
      actions: [{ type: 'FLAG_MANUAL_REVIEW', metadata: 'Below expectations' }],
      conflictStrategy: 'ANNOTATE_ONLY',
      stopProcessing: false,
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'guardrail-new-hire',
    name: 'New hire exclusion',
    description: 'YOE < 1 year: 0% increase, manual review (not in standard cycle).',
    stage: 'EXCLUSION_GUARDRAIL',
    policyType: 'Guardrail',
    policy: {
      templateKey: 'guardrail-new-hire',
      name: 'New hire exclusion',
      description: 'YOE < 1 year: 0% increase, manual review.',
      status: 'active',
      stage: 'EXCLUSION_GUARDRAIL',
      policyType: 'Guardrail',
      priority: 8,
      targetScope: {},
      conditions: { and: [{ '<': [{ var: 'yoe' }, 1] }] },
      actions: [
        { type: 'ZERO_OUT_INCREASE' },
        { type: 'FLAG_MANUAL_REVIEW', metadata: 'New hire (< 1 YOE)' },
      ],
      conflictStrategy: 'FORCE_RESULT',
      stopProcessing: true,
      createdAt: ts(),
      updatedAt: ts(),
    },
  },

  // ─── MODIFIER ─────────────────────────────────────────────────────────────
  {
    templateKey: 'modifier-wrvu60',
    name: 'High wRVU productivity modifier',
    description: 'If wRVU percentile > 60, add +1.0% to base increase.',
    stage: 'MODIFIER',
    policyType: 'Modifier',
    policy: {
      templateKey: 'modifier-wrvu60',
      name: 'High wRVU productivity modifier',
      description: 'If wRVU percentile > 60, add +1.0% to base increase.',
      status: 'active',
      stage: 'MODIFIER',
      policyType: 'Modifier',
      priority: 10,
      targetScope: {},
      conditions: { and: [{ '>': [{ var: 'wrvuPercentile' }, 60] }] },
      actions: [{ type: 'ADD_INCREASE_PERCENT', value: 1.0 }],
      conflictStrategy: 'ADDITIVE_MODIFIER',
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'modifier-wrvu80',
    name: 'Very high wRVU modifier',
    description: 'wRVU percentile > 80 adds +1.5% for top producers.',
    stage: 'MODIFIER',
    policyType: 'Modifier',
    policy: {
      templateKey: 'modifier-wrvu80',
      name: 'Very high wRVU modifier',
      description: 'wRVU percentile > 80 adds +1.5% for top producers.',
      status: 'active',
      stage: 'MODIFIER',
      policyType: 'Modifier',
      priority: 5,
      targetScope: {},
      conditions: { and: [{ '>': [{ var: 'wrvuPercentile' }, 80] }] },
      actions: [{ type: 'ADD_INCREASE_PERCENT', value: 1.5 }],
      conflictStrategy: 'ADDITIVE_MODIFIER',
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'modifier-exceeds',
    name: 'Exceeds expectations modifier',
    description: 'Evaluation score 5 adds +0.5% for top performers.',
    stage: 'MODIFIER',
    policyType: 'Modifier',
    policy: {
      templateKey: 'modifier-exceeds',
      name: 'Exceeds expectations modifier',
      description: 'Evaluation score 5 adds +0.5% for top performers.',
      status: 'active',
      stage: 'MODIFIER',
      policyType: 'Modifier',
      priority: 15,
      targetScope: {},
      conditions: { and: [{ '===': [{ var: 'evaluationScore' }, 5] }] },
      actions: [{ type: 'ADD_INCREASE_PERCENT', value: 0.5 }],
      conflictStrategy: 'ADDITIVE_MODIFIER',
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'modifier-low-tcc-retention',
    name: 'Low TCC retention modifier',
    description: 'TCC below 25th percentile: +0.5% to support retention.',
    stage: 'MODIFIER',
    policyType: 'Modifier',
    policy: {
      templateKey: 'modifier-low-tcc-retention',
      name: 'Low TCC retention modifier',
      description: 'TCC below 25th percentile: +0.5% to support retention.',
      status: 'active',
      stage: 'MODIFIER',
      policyType: 'Modifier',
      priority: 20,
      targetScope: {},
      conditions: { and: [{ '<': [{ var: 'tccPercentile' }, 25] }] },
      actions: [{ type: 'ADD_INCREASE_PERCENT', value: 0.5 }],
      conflictStrategy: 'ADDITIVE_MODIFIER',
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'modifier-pcp',
    name: 'PCP division modifier',
    description: 'Primary Care / PCP division: +0.25% market adjustment.',
    stage: 'MODIFIER',
    policyType: 'Modifier',
    policy: {
      templateKey: 'modifier-pcp',
      name: 'PCP division modifier',
      description: 'Primary Care / PCP division: +0.25% market adjustment.',
      status: 'active',
      stage: 'MODIFIER',
      policyType: 'Modifier',
      priority: 25,
      targetScope: { divisions: ['PCP', 'Primary Care', 'Primary Care Physicians'] },
      actions: [{ type: 'ADD_INCREASE_PERCENT', value: 0.25 }],
      conflictStrategy: 'ADDITIVE_MODIFIER',
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'modifier-surgery',
    name: 'Surgical specialty modifier',
    description: 'Surgical specialties: +0.25% market premium.',
    stage: 'MODIFIER',
    policyType: 'Modifier',
    policy: {
      templateKey: 'modifier-surgery',
      name: 'Surgical specialty modifier',
      description: 'Surgical specialties: +0.25% market premium.',
      status: 'active',
      stage: 'MODIFIER',
      policyType: 'Modifier',
      priority: 25,
      targetScope: {
        specialties: ['General Surgery', 'Orthopedic Surgery', 'Cardiothoracic Surgery', 'Neurosurgery', 'Surgery'],
      },
      actions: [{ type: 'ADD_INCREASE_PERCENT', value: 0.25 }],
      conflictStrategy: 'ADDITIVE_MODIFIER',
      createdAt: ts(),
      updatedAt: ts(),
    },
  },

  // ─── CAP_FLOOR ─────────────────────────────────────────────────────────────
  {
    templateKey: 'cap-max6',
    name: 'Maximum increase cap 6%',
    description: 'Cap recommended increase at 6%.',
    stage: 'CAP_FLOOR',
    policyType: 'Cap/Floor',
    policy: {
      templateKey: 'cap-max6',
      name: 'Maximum increase cap 6%',
      description: 'Cap recommended increase at 6%.',
      status: 'active',
      stage: 'CAP_FLOOR',
      policyType: 'Cap/Floor',
      priority: 10,
      targetScope: {},
      actions: [{ type: 'CAP_INCREASE_PERCENT', value: 6 }],
      conflictStrategy: 'CAP_RESULT',
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'cap-max5',
    name: 'Conservative cap 5%',
    description: 'Cap recommended increase at 5% (tighter budget).',
    stage: 'CAP_FLOOR',
    policyType: 'Cap/Floor',
    policy: {
      templateKey: 'cap-max5',
      name: 'Conservative cap 5%',
      description: 'Cap recommended increase at 5%.',
      status: 'active',
      stage: 'CAP_FLOOR',
      policyType: 'Cap/Floor',
      priority: 10,
      targetScope: {},
      actions: [{ type: 'CAP_INCREASE_PERCENT', value: 5 }],
      conflictStrategy: 'CAP_RESULT',
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'floor-min2',
    name: 'Minimum increase floor 2%',
    description: 'Floor recommended increase at 2% (unless guardrail zeros).',
    stage: 'CAP_FLOOR',
    policyType: 'Cap/Floor',
    policy: {
      templateKey: 'floor-min2',
      name: 'Minimum increase floor 2%',
      description: 'Floor recommended increase at 2% (unless guardrail zeros).',
      status: 'active',
      stage: 'CAP_FLOOR',
      policyType: 'Cap/Floor',
      priority: 20,
      targetScope: {},
      actions: [{ type: 'FLOOR_INCREASE_PERCENT', value: 2 }],
      conflictStrategy: 'FLOOR_RESULT',
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'floor-min3-new',
    name: 'New physician floor 3%',
    description: 'Providers with YOE < 3 get minimum 3% (accelerate early career).',
    stage: 'CAP_FLOOR',
    policyType: 'Cap/Floor',
    policy: {
      templateKey: 'floor-min3-new',
      name: 'New physician floor 3%',
      description: 'Providers with YOE < 3 get minimum 3%.',
      status: 'active',
      stage: 'CAP_FLOOR',
      policyType: 'Cap/Floor',
      priority: 15,
      targetScope: { yoeMax: 3 },
      actions: [{ type: 'FLOOR_INCREASE_PERCENT', value: 3 }],
      conflictStrategy: 'FLOOR_RESULT',
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'floor-min2.5',
    name: 'Minimum floor 2.5%',
    description: 'General floor at 2.5% for all providers.',
    stage: 'CAP_FLOOR',
    policyType: 'Cap/Floor',
    policy: {
      templateKey: 'floor-min2.5',
      name: 'Minimum floor 2.5%',
      description: 'General floor at 2.5% for all providers.',
      status: 'active',
      stage: 'CAP_FLOOR',
      policyType: 'Cap/Floor',
      priority: 20,
      targetScope: {},
      actions: [{ type: 'FLOOR_INCREASE_PERCENT', value: 2.5 }],
      conflictStrategy: 'FLOOR_RESULT',
      createdAt: ts(),
      updatedAt: ts(),
    },
  },

  // ─── CUSTOM_MODEL (Tiered compensation) ───────────────────────────────────
  {
    templateKey: 'fixed-pct-cardiology',
    name: 'Cardiology – 4% fixed increase',
    description: 'Cardiologists receive a flat 4% increase. Target: Cardiology / Cardiovascular Disease only.',
    stage: 'CUSTOM_MODEL',
    policyType: 'Custom model',
    policy: {
      templateKey: 'fixed-pct-cardiology',
      name: 'Cardiology – 4% fixed increase',
      description: 'Cardiologists receive a flat 4% increase.',
      status: 'active',
      stage: 'CUSTOM_MODEL',
      policyType: 'Custom model',
      priority: 12,
      targetScope: { specialties: ['Cardiology', 'Cardiovascular Disease'] },
      actions: [],
      conflictStrategy: 'REPLACE_BASE_RESULT',
      modelConfig: { type: 'FIXED_PERCENT', fixedIncreasePercent: 4 },
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'tier-base-salary-cardiology',
    name: 'Cardiology – Base salary by YOE tier',
    description: 'For Cardiology: fixed base salary by years of experience (0–4, 5–9, 10+). Adjust specialties and tiers.',
    stage: 'CUSTOM_MODEL',
    policyType: 'Custom model',
    policy: {
      templateKey: 'tier-base-salary-cardiology',
      name: 'Cardiology – Base salary by YOE tier',
      description: 'For Cardiology: fixed base salary by years of experience.',
      status: 'active',
      stage: 'CUSTOM_MODEL',
      policyType: 'Custom model',
      priority: 10,
      targetScope: { specialties: ['Cardiology', 'Cardiovascular Disease'] },
      actions: [],
      conflictStrategy: 'REPLACE_BASE_RESULT',
      modelConfig: {
        type: 'YOE_TIER_BASE_SALARY',
        tierBaseSalaryRows: [
          { minYoe: 0, maxYoe: 4, label: '0–4 YOE', baseSalary: 280000 },
          { minYoe: 4.01, maxYoe: 9, label: '5–9 YOE', baseSalary: 320000 },
          { minYoe: 9.01, maxYoe: 999, label: '10+ YOE', baseSalary: 360000 },
        ],
      },
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'tier-base-salary-division',
    name: 'Division – Base salary by YOE tier',
    description: 'Target a division (e.g. PCP, Surgery) with tiered base salary by YOE. Edit division list and tier amounts.',
    stage: 'CUSTOM_MODEL',
    policyType: 'Custom model',
    policy: {
      templateKey: 'tier-base-salary-division',
      name: 'Division – Base salary by YOE tier',
      description: 'Target division with tiered base salary by YOE.',
      status: 'active',
      stage: 'CUSTOM_MODEL',
      policyType: 'Custom model',
      priority: 15,
      targetScope: { divisions: ['PCP', 'Primary Care'] },
      actions: [],
      conflictStrategy: 'REPLACE_BASE_RESULT',
      modelConfig: {
        type: 'YOE_TIER_BASE_SALARY',
        tierBaseSalaryRows: [
          { minYoe: 0, maxYoe: 3, label: '0–3 YOE', baseSalary: 200000 },
          { minYoe: 3.01, maxYoe: 7, label: '4–7 YOE', baseSalary: 220000 },
          { minYoe: 7.01, maxYoe: 999, label: '8+ YOE', baseSalary: 240000 },
        ],
      },
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'tier-increase-pct-specialty',
    name: 'Specialty – Increase % by YOE tier',
    description: 'Target specific specialties with tiered increase % (e.g. 3.5% for 0–5 YOE, 4% for 5–10, 4.5% for 10+).',
    stage: 'CUSTOM_MODEL',
    policyType: 'Custom model',
    policy: {
      templateKey: 'tier-increase-pct-specialty',
      name: 'Specialty – Increase % by YOE tier',
      description: 'Target specialties with tiered increase % by YOE.',
      status: 'active',
      stage: 'CUSTOM_MODEL',
      policyType: 'Custom model',
      priority: 15,
      targetScope: { specialties: ['Internal Medicine', 'Family Medicine'] },
      actions: [],
      conflictStrategy: 'REPLACE_BASE_RESULT',
      modelConfig: {
        type: 'YOE_TIER_TABLE',
        tierRows: [
          { minYoe: 0, maxYoe: 5, label: '0–5 YOE', increasePercent: 3.5 },
          { minYoe: 5.01, maxYoe: 10, label: '5–10 YOE', increasePercent: 4 },
          { minYoe: 10.01, maxYoe: 999, label: '10+ YOE', increasePercent: 4.5 },
        ],
      },
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
  {
    templateKey: 'tier-increase-pct-general-pediatrics',
    name: 'General Pediatrics – Increase % by YOE tier',
    description: 'Years of experience tiers apply only to General Pediatrics / Pediatrics (surgically targeted).',
    stage: 'CUSTOM_MODEL',
    policyType: 'Custom model',
    policy: {
      templateKey: 'tier-increase-pct-general-pediatrics',
      name: 'General Pediatrics – Increase % by YOE tier',
      description: 'YOE-based increase tiers for General Pediatrics and Pediatrics only.',
      status: 'active',
      stage: 'CUSTOM_MODEL',
      policyType: 'Custom model',
      priority: 14,
      targetScope: { specialties: ['General Pediatrics', 'Pediatrics'] },
      actions: [],
      conflictStrategy: 'REPLACE_BASE_RESULT',
      modelConfig: {
        type: 'YOE_TIER_TABLE',
        tierRows: [
          { minYoe: 0, maxYoe: 2, label: '0–2 YOE', increasePercent: 3.5 },
          { minYoe: 2.01, maxYoe: 5, label: '3–5 YOE', increasePercent: 4 },
          { minYoe: 5.01, maxYoe: 10, label: '6–10 YOE', increasePercent: 4.25 },
          { minYoe: 10.01, maxYoe: 999, label: '11+ YOE', increasePercent: 4.5 },
        ],
      },
      createdAt: ts(),
      updatedAt: ts(),
    },
  },
];
