/**
 * Seed canonical table. Ship as code for auditability; can be replaced by JSON load later.
 */

import type { CanonicalSpecialtyRecord } from './types';

export const SPECIALTY_GROUPING_SEED = [
  {
    specialtyGroup: 'Primary Care',
    canonicalSpecialty: 'Family Medicine',
    synonyms: ['Family Practice', 'FM', 'Primary Care', 'General Practice', 'GP'],
    keywords: ['family', 'primary'],
    priority: 10,
    activeFlag: true,
    notes: 'Primary ambulatory general practice',
  },
  {
    specialtyGroup: 'Primary Care',
    canonicalSpecialty: 'Internal Medicine - Primary Care',
    synonyms: ['IM Primary', 'Primary IM', 'Outpatient Internal Medicine'],
    keywords: ['internal', 'primary'],
    priority: 8,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Medical',
    canonicalSpecialty: 'Cardiology - General',
    synonyms: ['General Cardiology', 'Cardiology', 'Cards'],
    keywords: ['cardiology', 'cardiac'],
    priority: 10,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Medical',
    canonicalSpecialty: 'Gastroenterology',
    synonyms: ['GI', 'Gastro'],
    keywords: ['gastro', 'gi'],
    priority: 10,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Medical',
    canonicalSpecialty: 'Pulmonary Medicine',
    synonyms: ['Pulmonology', 'Lung', 'Pulmonary'],
    keywords: ['pulmonary', 'pulmonology', 'lung'],
    priority: 10,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Medical',
    canonicalSpecialty: 'Nephrology',
    synonyms: ['Renal', 'Kidney'],
    keywords: ['nephrology', 'renal'],
    priority: 10,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Medical',
    canonicalSpecialty: 'Endocrinology',
    synonyms: ['Endocrine', 'Diabetes'],
    keywords: ['endocrinology'],
    priority: 10,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Medical',
    canonicalSpecialty: 'Rheumatology',
    synonyms: ['Rheum'],
    keywords: ['rheumatology'],
    priority: 10,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Medical',
    canonicalSpecialty: 'Infectious Disease',
    synonyms: ['ID', 'Infectious Diseases'],
    keywords: ['infectious'],
    priority: 10,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Medical',
    canonicalSpecialty: 'Hematology',
    synonyms: ['Heme'],
    keywords: ['hematology', 'heme'],
    priority: 10,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Medical',
    canonicalSpecialty: 'Medical Oncology',
    synonyms: ['Oncology - Medical', 'Heme/Onc'],
    keywords: ['oncology', 'heme'],
    priority: 9,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Medical',
    canonicalSpecialty: 'Neurology',
    synonyms: ['Neuro'],
    keywords: ['neurology'],
    priority: 10,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Medical',
    canonicalSpecialty: 'Dermatology',
    synonyms: ['Derm'],
    keywords: ['dermatology'],
    priority: 10,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Surgical',
    canonicalSpecialty: 'General Surgery',
    synonyms: ['GS', 'Gen Surg'],
    keywords: ['surgery', 'surgical'],
    priority: 12,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Surgical',
    canonicalSpecialty: 'Orthopedic Surgery',
    synonyms: ['Ortho', 'Orthopedics', 'Orthopaedic Surgery'],
    keywords: ['orthopedic', 'orthopaedic'],
    priority: 12,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Surgical',
    canonicalSpecialty: 'Neurosurgery',
    synonyms: ['Neurosurg', 'CNS Surgery'],
    keywords: ['neurosurgery'],
    priority: 12,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Surgical',
    canonicalSpecialty: 'Urology',
    synonyms: ['Urologic Surgery'],
    keywords: ['urology', 'urologic'],
    priority: 12,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Surgical',
    canonicalSpecialty: 'Cardiothoracic Surgery',
    synonyms: ['CT Surgery', 'Cardiac Surgery', 'Thoracic Surgery'],
    keywords: ['cardiothoracic', 'thoracic', 'cardiac'],
    priority: 14,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Surgical',
    canonicalSpecialty: 'Plastic Surgery',
    synonyms: ['Plastic', 'Reconstructive Surgery'],
    keywords: ['plastic'],
    priority: 12,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Surgical',
    canonicalSpecialty: 'Vascular Surgery',
    synonyms: ['Vascular'],
    keywords: ['vascular'],
    priority: 12,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Hospital Based',
    canonicalSpecialty: 'Radiology - Interventional',
    synonyms: ['Interventional Rad', 'Interventional Radiology', 'IR'],
    keywords: ['interventional', 'radiology'],
    priority: 14,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Hospital Based',
    canonicalSpecialty: 'Radiology - Diagnostic',
    synonyms: ['Diagnostic Radiology', 'DR', 'Imaging'],
    keywords: ['radiology', 'diagnostic'],
    priority: 11,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Hospital Based',
    canonicalSpecialty: 'Emergency Medicine',
    synonyms: ['EM', 'ER', 'Emergency Dept'],
    keywords: ['emergency'],
    priority: 12,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Hospital Based',
    canonicalSpecialty: 'Hospitalist - Internal Medicine',
    synonyms: ['Hospitalist', 'IM Hospitalist', 'Acute Care'],
    keywords: ['hospitalist'],
    priority: 13,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Hospital Based',
    canonicalSpecialty: 'Critical Care',
    synonyms: ['ICU', 'Intensivist', 'Critical Care Medicine'],
    keywords: ['critical', 'icu', 'intensivist'],
    priority: 12,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Hospital Based',
    canonicalSpecialty: 'Anesthesiology',
    synonyms: ['Anesthesia', 'Anaesthesiology'],
    keywords: ['anesthesiology', 'anaesthesia'],
    priority: 11,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Pediatric Medical',
    canonicalSpecialty: 'Pediatrics - General',
    synonyms: ['General Pediatrics', 'Pediatrics', 'Peds'],
    keywords: ['pediatrics', 'pediatric', 'peds'],
    priority: 10,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Pediatric Medical',
    canonicalSpecialty: 'Pediatrics - Cardiology',
    synonyms: ['Peds Cardiology', 'Pediatric Cardiology', 'Pediatric Cardiol'],
    keywords: ['pediatric', 'cardiology'],
    priority: 14,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Pediatric Medical',
    canonicalSpecialty: 'Pediatrics - Endocrinology',
    synonyms: ['Peds Endocrine', 'Pediatric Endocrinology'],
    keywords: ['pediatric', 'endocrinology'],
    priority: 13,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Pediatric Medical',
    canonicalSpecialty: 'Pediatrics - Gastroenterology',
    synonyms: ['Peds GI', 'Pediatric Gastroenterology'],
    keywords: ['pediatric', 'gastro'],
    priority: 13,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Pediatric Surgical',
    canonicalSpecialty: 'Pediatrics - General Surgery',
    synonyms: ['Pediatric General Surgery', 'Peds GS'],
    keywords: ['pediatric', 'surgery'],
    priority: 14,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Pediatric Surgical',
    canonicalSpecialty: 'Pediatrics - Orthopedic Surgery',
    synonyms: ['Pediatric Orthopedics', 'Peds Ortho'],
    keywords: ['pediatric', 'orthopedic'],
    priority: 14,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Pediatric Surgical',
    canonicalSpecialty: 'Pediatrics - Urology',
    synonyms: ['Pediatric Urology', 'Peds Urology'],
    keywords: ['pediatric', 'urology'],
    priority: 14,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Pediatric Surgical',
    canonicalSpecialty: 'Pediatrics - Plastic Surgery',
    synonyms: ['Pediatric Plastic Surgery'],
    keywords: ['pediatric', 'plastic'],
    priority: 14,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Pediatric Hospital Based',
    canonicalSpecialty: 'Pediatrics - Emergency Medicine',
    synonyms: ['Pediatric EM', 'Peds Emergency', 'PEDs ER'],
    keywords: ['pediatric', 'emergency'],
    priority: 14,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Pediatric Hospital Based',
    canonicalSpecialty: 'Pediatrics - Radiology',
    synonyms: ['Pediatric Radiology', 'Peds Rad'],
    keywords: ['pediatric', 'radiology'],
    priority: 14,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Pediatric Hospital Based',
    canonicalSpecialty: 'Pediatrics - Hospitalist',
    synonyms: ['Pediatric Hospitalist', 'Peds Hospitalist'],
    keywords: ['pediatric', 'hospitalist'],
    priority: 14,
    activeFlag: true,
  },
  {
    specialtyGroup: 'Pediatric Hospital Based',
    canonicalSpecialty: 'Neonatology',
    synonyms: ['Neonatal', 'NICU', 'Peds Neonatology'],
    keywords: ['neonatology', 'neonatal', 'nicu'],
    priority: 14,
    activeFlag: true,
  },
  {
    specialtyGroup: 'APPs - General',
    canonicalSpecialty: 'Certified Registered Nurse Anesthetist',
    synonyms: ['CRNA', 'Nurse Anesthetist', 'Nurse Anesthesist'],
    keywords: ['crna', 'anesthetist'],
    priority: 15,
    activeFlag: true,
  },
  {
    specialtyGroup: 'APPs - General',
    canonicalSpecialty: 'Certified Nurse Midwife',
    synonyms: ['CNM', 'Midwife', 'Nurse Midwife'],
    keywords: ['cnm', 'midwife'],
    priority: 14,
    activeFlag: true,
  },
  {
    specialtyGroup: 'APPs - General',
    canonicalSpecialty: 'Anesthesiologist Assistant',
    synonyms: ['CAA', 'Anesthesia Assistant'],
    keywords: ['caa', 'anesthesiologist assistant'],
    priority: 14,
    activeFlag: true,
  },
  {
    specialtyGroup: 'APPs - General',
    canonicalSpecialty: 'Physician Assistant - General',
    synonyms: ['PA', 'Physician Assistant', 'PA-C'],
    keywords: ['assistant', 'physician assistant'],
    priority: 8,
    activeFlag: true,
  },
  {
    specialtyGroup: 'APPs - General',
    canonicalSpecialty: 'Nurse Practitioner - General',
    synonyms: ['NP', 'Nurse Practitioner', 'ARNP'],
    keywords: ['practitioner', 'nurse practitioner'],
    priority: 8,
    activeFlag: true,
  },
].filter((r) => r.activeFlag) as CanonicalSpecialtyRecord[];
